/* Cenário base — All'Antico Panino Loja 206 (port de sim-core.js, linhas 40-101). */

import type { SimConfig } from './types'

export function baseConfig(): SimConfig {
  return {
    ops: 2,
    fixedEq: ['', ''],
    rate: 30,
    demandCurve: 'both',
    maxItems: 3,
    groupBias: 30,
    tol: 12,
    pickupTimeout: 30,
    sla: 15,
    opCost: 25,
    fixedCost: 800,
    walkSpeed: 30,
    custSpeed: 40,
    payTime: 1.0,
    capacity: { forno: 2, estufa: 2 },
    cfgV: 2,
    menu: [
      {
        id: 'spaccata',
        name: 'La Spaccata',
        prob: 0.55,
        price: 92,
        cat: 'lanche',
        pao: 1,
        steps: [
          { type: 'montagem', time: 2.5 },
          { type: 'vitrine', time: 0.4 },
        ],
      },
      { id: 'panino', name: 'Panino Simples', prob: 0.3, price: 45, cat: 'lanche', pao: 1, steps: [{ type: 'montagem', time: 2.0 }] },
      { id: 'bebida', name: 'Bebida', prob: 0.15, price: 15, cat: 'bebida', pao: 0, steps: [{ type: 'bibite', time: 0.5 }] },
    ],
    bread: {
      mode: 'propria',
      batchSize: 20,
      mixTime: 18,
      proofTime: 75,
      bakeTime: 22,
      breadStart: 30,
      target: 60,
      flourStart: 50,
      flourPerBread: 0.12,
      flourPrice: 6.5,
      extraPerBread: 0.6,
      energyPerBatch: 7,
      bakerCost: 28,
      bakerHours: 8,
      invest: 15700,
      deprecMonths: 36,
      rentM2: 250,
      tercPrice: 4.8,
      tercFrete: 25,
      tercQty: 140,
      storageCap: 120,
      shiftStart: 600,
      shiftHours: 8,
      shifts: 1,
      hybridOwnPct: 60,
      investBatedeira: 6200,
      lifeBatedeira: 60,
      investEstufa: 5400,
      lifeEstufa: 48,
      investForno: 4100,
      lifeForno: 36,
    },
    inv: { bibiteStart: 60, bibiteCap: 72, vitrineCap: 24 },
    seed: 42,
  }
}
